### ISSUE TITLE
Create docker-compose

### ISSUE THREAD

**Issue by pedromsmoreira** [the-pet-projects/toggling-it#17]
Create docker-compose file for an easier environment setup.

Images needed:

- Neo4j
- Kafka
- Zookeeper
- Redis (may not be needed)

**Comment by joao-r-reis** [comment]
Created docker compose files with only the web api for now - https://github.com/the-pet-projects/toggling-it/commit/eee6fbec570b6e931c17fed8ed8396e15c6f781b 
Will add more services/databases to the file when we have have more info.
